---

- name: make and copy env file
  template:
    src: env.j2
    dest: '{{ projects[PROJECT].location }}/.env'
    mode: 0644

- name: build develop
  make:
    chdir: '{{ projects[PROJECT].location }}'
    target: build

- name: run develop
  make:
    chdir: '{{ projects[PROJECT].location }}'
    target: start
