---

- name: Pull and run new release
  hosts: '{{ project }}'
  vars:
    PROJECT: "{{ project }}"
    VERSION: "{{ ver|default(0) }}"

  roles:
    - user-present
    - run-utils-present
    - configure-and-run-apps
