---

- name: copy docker-compose
  template:
    src: '{{ projects[PROJECT].location }}/{{ projects[PROJECT].release.docker }}/{{ projects[PROJECT].roles[ROLE] }}/docker-compose.run.j2'
    dest: '/home/{{ projects[PROJECT].roles[ROLE].user }}/docker-compose.yml'
    owner: '{{ projects[PROJECT].roles[ROLE].user }}'
    group: '{{ projects[PROJECT].roles[ROLE].user }}'
    mode: 0644
- name: copy Makefile
  copy:
    src: '{{ projects[PROJECT].location }}/{{ projects[PROJECT].release.makefile }}'
    dest: '/home/{{ projects[PROJECT].roles[ROLE].user }}/Makefile'
    owner: '{{ projects[PROJECT].roles[ROLE].user }}'
    group: '{{ projects[PROJECT].roles[ROLE].user }}'
    mode: 0644
- name: make and copy env file
  template:
    src: env.j2
    dest: '/home/{{ projects[PROJECT].roles[ROLE].user }}/.env'
    owner: '{{ projects[PROJECT].roles[ROLE].user }}'
    group: '{{ projects[PROJECT].roles[ROLE].user }}'
    mode: 0644
