---

- name: docker login
  make:
    chdir: '/home/{{ projects[PROJECT].roles[ROLE].user }}'
    target: login
- name: docker pull
  make:
    chdir: '/home/{{ projects[PROJECT].roles[ROLE].user }}'
    target: pull
- name: docker-compose stop
  make:
    chdir: '/home/{{ projects[PROJECT].roles[ROLE].user }}'
    target: stop
- name: docker-compose configure
  make:
    chdir: '/home/{{ projects[PROJECT].roles[ROLE].user }}'
    target: configure
- name: docker-compose start
  make:
    chdir: '/home/{{ projects[PROJECT].roles[ROLE].user }}'
    target: start
