---

- name: remove git from docker image
  file:
    path: '{{ projects[PROJECT].location }}/{{ item.location }}/.git/'
    state: absent
  with_items: '{{ projects[PROJECT].repos }}'

- name: make and copy env file
  template:
    src: env.j2
    dest: '{{ projects[PROJECT].location }}/.env'
    mode: 0644

- name: docker login
  make:
    chdir: '{{ projects[PROJECT].location }}'
    target: login

- name: build images and push them to a private repo
  docker_image:
    path: '{{ projects[PROJECT].location }}/{{ item.context }}'
    dockerfile: '{{ item.dockerfile }}'
    name: '{{ projects[PROJECT].docker_project }}/{{ item.image }}'
    tag: '{{ (ROLE=="test") | ternary(VERSION, projects[PROJECT].roles[ROLE].branch) }}'
    push: yes
    force: yes
  with_items: '{{ projects[PROJECT].dockers }}'

- name: docker logout
  make:
    chdir: '{{ projects[PROJECT].location }}'
    target: logout
